apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsI
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opsI
  template:
    metadata:
      labels:
        name: opsI
    spec:
      serviceAccountName: opsI
      containers:
        - name: opsI
          # Replace this with the built image name
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - opsI
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "opsI"
