kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opsI
subjects:
- kind: ServiceAccount
  name: opsI
roleRef:
  kind: Role
  name: opsI
  apiGroup: rbac.authorization.k8s.io
